openapi: 3.0.0
info:
  title: SDM SQL Schema Generation
  version: 0.1.0
  description: FastAPI application for SDM Quality Testing

paths:
  /version:
    get:
      summary: Get version information
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  doc:
                    type: string
                  git_hash:
                    type: string
                  version:
                    type: string
                  release_date:
                    type: string
                  uptime:
                    type: string

  /generate:
    post:
      summary: Generating a SQL Schema
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                url:
                  type: string
              required:
                - url
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

components:
  schemas:
    SDMQualityTesting:
      type: object
      properties:
        data_model_repo_url:
          type: string
        mail:
          type: string
        last_test_number:
          type: integer
      required:
        - data_model_repo_url
        - mail
        - last_test_number